name: Build Typst document
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  compile_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Compile pdf
        run: typst c main.typ

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

